[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool]
[tool.poetry]
authors = ["Your Name <you@example.com>"]
description = ""
name = "poker-dev-env"
version = "0.1.0"
[tool.poetry.dependencies]
poker-game-runner = "^0.1.15"
python = "^3.8"
[tool.poetry.dev-dependencies]
